export const MATS_SEARCH_OPTIONS = {
    
    'Материал': [
        'Гумени',
        'Мокетни',
        'Универсални стелки'
    ],
    
    'Марки': {
        'AUDI': [
            '80',
            '100',
            'A1',
            'A3',
            'A4',
            'A5',
            'A6',
            'A7',
            'A8',
            'Q2',
            'Q3',
            'Q4',
            'Q5',
            'Q7',
            'Q8',
            'R8',
            'RS3',
            'RS4',
            'RS5',
            'RS6',
            'RS7',
            'RSQ3',
            'RSQ5',
            'RSQ8',
            'TT',
            'TT RS'
        ],
        
        'BMW': [
            
            'Серия 1',
            'Серия 2',
            'Серия 3',
            'Серия 4',
            'Серия 5',
            'Серия 6',
            'Серия 7',
            'Серия 8',
            'Серия X',
            'Серия I',
            'Серия IX',
            'Серия Z',
            'M2',
            'M3',
            'M4',
            'M5',
            'M6',
            'X3M',
            'X4M',
            'X5M',
            'X6M',
            'XM',
        ],
        
        'VW': [
            
            'Amarok',
            'Arteon',
            'Atlas',
            'Beetle',
            'Bora',
            'Caddy',
            'Corrado',
            'Crafter',
            'Cross Polo',
            'Cross Up',
            'e-Golf',
            'EOS',
            'FOX',
            'Golf',
            'Golf Sportsvan',
            'ID.3',
            'ID.4',
            'ID.5',
            'iD.7',
            'ID.Buzz',
            'Jetta',
            'LT',
            'Lupo',
            'New Beetle',
            'Passat',
            'Polo',
            'Polo Classic',
            'Scirocco',
            'Sharan',
            'T-Cross',
            'T-roc',
            'T2',
            'T3',
            'T4',
            'T5',
            'T6',
            'T7',
            'Taigo',
            'Taro',
            'Tayron',
            'Tiguan',
            'Touareg',
            'Touran',
            'Up',
            'Vento',
        ],
        'MERCEDES-BENZ': [],
        'OPEL': [],
        'TOYOTA': [],
        'HONDA': [],
        'PEUGEOT': [],
        'FORD': [],
        'RENAULT': [],
        'NISSAN': [],
        'MAZDA': [],
        'FIAT': [],
        'HYUNDAI': [],
        'CITROËN': [],
        'SKODA': [],
        'VOLVO': [],
        'DACIA': [],
        'MITSUBISHI': [],
        'KIA': [],
        'JEEP': [],
        'SUBARU': [],
        'SEAT': [],
        'SUZUKI': [],
        'ALFA ROMEO': [],
        'CHEVROLET': [],
        'LAND ROVER': [],
        'MINI': [],
        'FORD USA': [],
        'PORSCHE': [],
        'LEXUS': [],
        'CHRYSLER': [],
        'IVECO': [],
        'JAGUAR': [],
        'SAAB': [],
        'GREAT WALL': [],
        'DAIHATSU': [],
        'INFINITI': [],
        'LADA': [],
        'DODGE': [],
        'LANCIA': [],
        'SSANGYONG': [],
        'TESLA': [],
        'DAEWOO': [],
        'SMART': [],
        'DR': [],
        'ROVER': [],
        'ISUZU': [],
        'CADILLAC': []
    }
};