export const MATS_SEARCH_OPTIONS = {
    
    'Материал': [
        'Гумени',
        'Мокетни',
        'Универсални стелки'
    ],
    
    'Марки': {
        'AUDI': [
            '80',
            '100',
            'A1',
            'A3',
            'A4',
            'A5',
            'A6',
            'A7',
            'A8',
            'Q2',
            'Q3',
            'Q4',
            'Q5',
            'Q7',
            'Q8',
            'R8',
            'RS3',
            'RS4',
            'RS5',
            'RS6',
            'RS7',
            'RSQ3',
            'RSQ5',
            'RSQ8',
            'TT',
            'TT RS'
        ],
        
        'BMW': [
            
            'Серия 1',
            'Серия 2',
            'Серия 3',
            'Серия 4',
            'Серия 5',
            'Серия 6',
            'Серия 7',
            'Серия 8',
            'Серия X',
            'Серия I',
            'Серия IX',
            'Серия Z',
            'M2',
            'M3',
            'M4',
            'M5',
            'M6',
            'X3M',
            'X4M',
            'X5M',
            'X6M',
            'XM',
        ],
        
        'VW': [
            
            'Amarok',
            'Arteon',
            'Atlas',
            'Beetle',
            'Bora',
            'Caddy',
            'Corrado',
            'Crafter',
            'Cross Polo',
            'Cross Up',
            'e-Golf',
            'EOS',
            'FOX',
            'Golf',
            'Golf Sportsvan',
            'ID.3',
            'ID.4',
            'ID.5',
            'iD.7',
            'ID.Buzz',
            'Jetta',
            'LT',
            'Lupo',
            'New Beetle',
            'Passat',
            'Polo',
            'Polo Classic',
            'Scirocco',
            'Sharan',
            'T-Cross',
            'T-roc',
            'T2',
            'T3',
            'T4',
            'T5',
            'T6',
            'T7',
            'Taigo',
            'Taro',
            'Tayron',
            'Tiguan',
            'Touareg',
            'Touran',
            'Up',
            'Vento',
        ],
        'MERCEDES-BENZ': [
            '110',
            '111',
            '114',
            '115',
            '116',
            '123',
            '124',
            '126',
            '126-260',
            '150',
            '170',
            '180',
            '190',
            '200',
            '220',
            '230',
            '240',
            '250',
            '280',
            '300',
            '320',
            '350',
            '380',
            '420',
            '450',
            '500',
            '560',
            '600',
            'A140',
            'A150',
            'A160',
            'A170',
            'A180',
            'A190',
            'A200',
            'A220',
            'A250',
            'A35',
            'A45',
            'A45 AMG',
            'AMG GT',
            'AMG GT C',
            'AMG GT R',
            'AMG GT S',
            'B150',
            'B160',
            'B170',
            'B180',
            'B200',
            'B220',
            'B250',
            'C160',
            'C180',
            'C200',
            'C220',
            'C230',
            'C240',
            'C250',
            'C270',
            'C280',
            'C30 AMG',
            'C300',
            'C32 AMG',
            'C320',
            'C350',
            'C36 AMG',
            'C400',
            'C43 AMG',
            'C450 AMG',
            'C55 AMG',
            'C63 AMG',
            'CL420',
            'CL500',
            'CL55 AMG',
            'CL600',
            'CL63 AMG',
            'CL65 AMG',
            'CLA180',
            'CLA200',
            'CLA220',
            'CLA250',
            'CLA350',
            'CLA350 AMG',
            'CLA45 AMG',
            'CLC160',
            'CLC180',
            'CLC200',
            'CLC220',
            'CLC230',
            'CLC250',
            'CLC350',
            'CLE',
            'CLK55 AMG',
            'CL63 AMG',
            'CLS220',
            'CLS250',
            'CLS300',
            'CLS320',
            'CLS350',
            'CLS400',
            'CLS450',
            'CLS500',
            'CLS53 AMG',
            'CLS55 AMG',
            'CLS550',
            'CLS63 AMG',
            'E220',
            'E220',
            'E230',
            'E240',
            'E250',
            'E260',
            'E270',
            'E280',
            'E290',
            'E300',
            'E320',
            'E350',
            'E36 AMG',
            'E400',
            'E420',
            'E43 AMG',
            'E430',
            'E450',
            'E50 AMG',
            'E500',
            'E53 AMG',
            'E55',
            'E55 AMG',
            'E60',
            'E60 AMG',
            'E63 AMG',
            'EQA',
            'EQB',
            'EQC',
            'EQE',
            'EQS',
            'EQV',
            'G230',
            'G240',
            'G250',
            'G270',
            'G280',
            'G290',
            'G300',
            'G320',
            'G350',
            'G36 AMG',
            'G400',
            'G450',
            'G500',
            'G55 AMG',
            'G580',
            'G63 AMG',
            'G65 AMG',
            'GL320',
            'GL350',
            'GL420',
            'GL450',
            'GL500',
            'GL63 AMG',
            'GLA180',
            'GLA200',
            'GLA220',
            'GLA250',
            'GLA45 AMG',
            'GLB',
            'GLC200',
            'GLC220',
            'GLC250',
            'GLC300',
            'GLC400',
            'GLC43 AMG',
            'GLC63 AMG',
            'GLE250',
            'GLE300',
            'GLE350',
            'GLE400',
            'GLE43 AMG',
            'GLE450',
            'GLE450 AMG',
            'GLE500',
            'GLE53 AMG',
            'GLE580',
            'GLE63 AMG',
            'GLE63S AMG',
            'GLE Coupe',
            'GLK',
            'GLS350',
            'GLS400',
            'GLS450',
            'GLS500',
            'GLS600',
            'GLS63 AMG',
            'GLS580',
            'GT',
            'GTS',
            'ML230',
            'ML250',
            'ML270',
            'ML280',
            'ML300',
            'ML320',
            'ML350',
            'ML400',
            'ML420',
            'ML430',
            'ML450',
            'ML500',
            'ML55 AMG',
            'ML550',
            'ML63 AMG',
            'R280',
            'R300',
            'R320',
            'R350',
            'R500',
            'R320',
            'S250',
            'S280',
            'S300',
            'S320',
            'S400',
            'S420',
            'S430',
            'S450',
            'S500',
            'S55 AMG',
            'S550',
            'S560',
            'S580',
            'S600',
            'S63 AMG',
            'S65',
            'S65 AMG',
            'S680',
            'SL400',
            'SL43 AMG',
            'SL500',
            'SL55 AMG',
            'SL600',
            'SL63 AMG',
            'SL65 AMG',
            'SLC',
            'SLK32 AMG',
            'SLK55 AMG',
            'SLR',
            'SLS AMG',
            'T-class',
            'V300',
            'Vaneo',
            'Viano',
            'X-Klasse',
            
        ],
        'OPEL': [
            'Adam',
            'Admiral',
            'Agila',
            'Ampera',
            'Antara',
            'Ascona',
            'Astra',
            'Calibra',
            'Campo',
            'Cascada',
            'Combo',
            'Commodore',
            'Corsa',
            'Crossland X',
            'Frontera',
            'Grandland',
            'Grandland X',
            'GT',
            'Insignia',
            'Kaddett',
            'Karl',
            'Manta',
            'Meriva',
            'Mokka',
            'Mokka X',
            'Monterey',
            'Omega',
            'Rekord',
            'Senator',
            'Signum',
            'Sintra',
            'Speedster',
            'Tigra',
            'Vectra',
            'Zafira',
            
            
        ],
        'TOYOTA': [
            '4runner',
            'Alphard',
            'Auris',
            'Avalon',
            'Avensis',
            'Avensis verso',
            'Aygo',
            'C-HR',
            'Camry',
            'Carina',
            'Celica',
            'Corolla',
            'Corolla Cross',
            'Corolla verso',
            'Crown',
            'Grand Highlander',
            'Harrier',
            'Highlander',
            'Hilux',
            'IQ',
            'Land cruiser',
            'Matrix',
            'Mirai',
            'Paseo',
            'Picnic',
            'Previa',
            'Prius',
            'Rav4',
            'Scion',
            'Sequoia',
            'Sienna',
            'Starlet',
            'Supra',
            'Tacoma',
            'Tercel',
            'Tundra',
            'Urban Cruiser',
            'Venza',
            'Verso',
            'Verso S',
            'Yaris',
            'Yaris Cross',
            'Yaris Verso',
            'Yaris',
        ],
        'HONDA': [
            'Accord',
            'Cbr',
            'City',
            'Civic',
            'Concerto',
            'Crx',
            'Crz',
            'Electric',
            'Element',
            'Fit',
            'Fr-v',
            'Hr-v',
            'Insight',
            'Jazz',
            'Legend',
            'Logo',
            'NSX',
            'Odyssey',
            'Pilot',
            'Prelude',
            'S2000',
            'Shuttle',
            'Stream',
            'ZR-V',
           
        ],
        'PEUGEOT': [
            '1007',
            '106',
            '107',
            '108',
            '2008',
            '205',
            '206',
            '207',
            '208',
            '3008',
            '301',
            '304',
            '306',
            '307',
            '308',
            '309',
            '4007',
            '4008',
            '403',
            '404',
            '405',
            '406',
            '407',
            '408',
            '5008',
            '505',
            '508',
            '508 RXH',
            '605',
            '607',
            '806',
            '807',
            'Bipper',
            'Expret',
            'Partner',
            'RCZ',
            'Rifter',
        ],
        'FORD': [
            'B-Max',
            'Bronco',
            'C-Max',
            'Capri',
            'Connect',
            'Consul',
            'Cougar',
            'Courier',
            'EcoSport',
            'Edge',
            'Escape',
            'Escort',
            'Excursion',
            'Expedition',
            'Explorer',
            'F150',
            'F250',
            'F350',
            'F450',
            'F750',
            'Fiesta',
            'Flex',
            'Focus',
            'Fusion',
            'Galaxy',
            'Granada',
            'Grand C-Max',
            'Ka',
            'Kuga',
            'Maverick',
            'Mercury',
            'Mondeo',
            'Mustang',
            'Mustang Mach-E',
            'Orion',
            'Probe',
            'Puma',
            'Ranger',
            'Raptor',
            'S-Max',
            'Scorpio',
            'Sierra',
            'Sportka',
            'Taunus',
            'Taurus',
            'Thunderbird',
            'Tourneo Connect',
            'Transit Custom',
            'Windstar',
            'Zephyr',
        ],
        'RENAULT': [
            '10',
            '11',
            '16',
            '19',
            '20',
            '25',
            '29',
            '4',
            '5',
            '8',
            '9',
            'Alpine',
            'Arkan',
            'Austral',
            'Avan time',
            'Captur',
            'Chamade',
            'Clio',
            'Duster',
            'Espace',
            'Express',
            'Fluence',
            'Grand espace',
            'Grand scenic',
            'K-ZE',
            'Kadjar',
            'Kangoo',
            'Koleos',
            'Laguna',
            'Laguna Coupe',
            'Latitude',
            'Megan',
            'Modus',
            'Rafale',
            'Safrane',
            'Scenic',
            'Scenic rx4',
            'Symbol',
            'Talisman',
            'Twingo',
            'Twizy',
            'Vel satis',
            'Wind',
            'Zoe',
            
        ],
        'NISSAN': [
            '100nx',
            '200sx',
            '240z',
            '280z',
            '300zx',
            '350z',
            '370z',
            'Acurra',
            'Almera',
            'Almera tino',
            'Altima',
            'Ariya',
            'Armada',
            'Bluebird',
            'Cube',
            'Frontier',
            'Gt-r',
            'Juke',
            'Kubistar',
            'Leaf',
            'Maxima',
            'Micra',
            'Murano',
            'Navara',
            'Note',
            'Pathfinder',
            'Patrol',
            'Pickup',
            'Pixo',
            'Primera',
            'Pulsar',
            'Qashqai',
            'Quest',
            'Rogue',
            'Sentra',
            'Serena',
            'Silvia',
            'Skyline',
            'Sunny',
            'Terrano',
            'Tiida',
            'Titan crew cab',
            'Titan king',
            'Versa',
            'X-trail',
            'Xterra',
            
        ],
        'MAZDA': [
            '121',
            '2',
            '3',
            '323',
            '5',
            '6',
            '626',
            '929',
            'B2200',
            'B2500',
            'BT-50',
            'CX-3',
            'CX-30',
            'CX-5',
            'CX-50',
            'CX-60',
            'CX-7',
            'CX-80',
            'CX-9',
            'CX-90',
            'Demio',
            'MX-30',
            'Mpv',
            'Mx-3',
            'Mx-5',
            'Mx-6',
            'Premacy',
            'Rx-7',
            'Rx-8',
            'Tribute',
            'Xedos',
            
        ],
        'FIAT': [
            '1100',
            '124',
            '125',
            '126',
            '131',
            '1400',
            '500',
            '500L',
            '500X',
            '500e',
            '600',
            'Albea',
            'Barchetta',
            'Brava',
            'Bravo',
            'Coupe',
            'Croma',
            'Doblo',
            'Fiorino',
            'Freemont',
            'Fullback',
            'Grande Panda',
            'Idea',
            'Linea',
            'Marea',
            'Multipa',
            'Palio',
            'Panda',
            'Punto',
            'Qubo',
            'Ritmo',
            'Scudo',
            'Sedici',
            'Seicento',
            'Stilo',
            'Strada',
            'Tipo',
            'Ulysse',
            'Uno',
          
        ],
        'HYUNDAI': [
            'Accent',
            'Atos',
            'Bayon',
            'Coupe',
            'Elantra',
            'Equus',
            'Galloper',
            'Genesis',
            'Getz',
            'Grandeur',
            'I10',
            'I20',
            'I30',
            'I40',
            'IX35',
            'IX55',
            'Inster',
            'Ioniq',
            'Ioniq 5',
            'Ioniq 6',
            'Ix20',
            'Kona',
            'Lantra',
            'Matrix',
            'Palisade',
            'Pony',
            'Santa Cruz',
            'Santa fe',
            'Santamo',
            'Sonta',
            'Starex',
            'Staria',
            'Terracan',
            'Trajet',
            'Tucson',
            'Veloster',
        ],
        'CITROËN': [
            'Ami',
            'Ax',
            'Berlingo',
            'Bx',
            'C-Zero',
            'C-Cross',
            'C-Elysee',
            'C1',
            'C2',
            'C3',
            'C3 Aircross',
            'C3 Picasso',
            'C3 Pluriel',
            'C4',
            'C4 Aircross',
            'C4 Cactus',
            'C4 Picasso',
            'C4X',
            'C5',
            'C5 Aircross',
            'C5X',
            'C6',
            'C8',
            'Cx',
            'DS3 Crossback',
            'DS4 Crossback',
            'DS7 Crossback',
            'DS3',
            'DS4',
            'DS5',
            'DS7',
            'DS',
            'Evasion',
            'Grand C4 Picasso',
            'Jumpy',
            'Nemo',
            'Saxo',
            'Spacetourer',
            'Xantia',
            'Xm',
            'Xsara',
            'Xsara Picasso',
            'Zx',
            
        ],
        'SKODA': [
            '100',
            '105',
            '120',
            'Citigo',
            'Elroq',
            'Enyaq',
            'Fabia',
            'Favorit',
            'Felicia',
            'Forman',
            'Kamiq',
            'Karoq',
            'Kodiaq',
            'Octavia',
            'Praktik',
            'Rapid',
            'Roomster',
            'Scala',
            'Superb',
            'Yeti',    
        ],
        'VOLVO': [
            '144',
            '1800es',
            '240',
            '244',
            '440',
            '460',
            '480',
            '740',
            '744',
            '850',
            '940',
            '960',
            'C30',
            'C40',
            'C70',
            'EX30',
            'EX90',
            'P1800',
            'S40',
            'S60',
            'S70',
            'S80',
            'S90',
            'V40',
            'V40 Cross Country',
            'V50',
            'V60',
            'V60 Cross Country',
            'V70',
            'V90',
            'V90 Cross Country',
            'XC40',
            'XC60',
            'XC70',
            'XC90',
        ],
        'DACIA': [
            '1310',
            'Bigster',
            'Dokker',
            'Duster',
            'Jogger',
            'Lodgy',
            'Logan',
            'Pickup',
            'Sandero',
            'Spring',
            
        ],
        'MITSUBISHI': [
            '3000gt',
            'ASX',
            'Attrage',
            'Carisma',
            'Colt',
            'Cordia',
            'Eclipse',
            'Eclipse Cross',
            'Galant',
            'Grandis',
            'L200',
            'Lancer',
            'Mirage',
            'Montero',
            'Outlander',
            'Pajero',
            'Pajero Pinin',
            'Pajero Sport',
            'RVR',
            'Sapporo',
            'Sigma',
            'Space Gear',
            'Space Runner',
            'Space Star',
            'Space Wagon',
            'Starion',
            'Tredia',
            
        ],
        'KIA': [
            'Avella Delta',
            'Carens',
            'Carnival',
            'Ceed',
            'Cerato',
            'EV6',
            'EV9',
            'Forte',
            'Joyce',
            'K3',
            'K4',
            'K5',
            'K7',
            'K8',
            'K9',
            'Magentis',
            'Mohave',
            'Morning',
            'Niro',
            'Opirus',
            'Optima',
            'Picanto',
            'Pride',
            'Pro Ceed',
            'Retona',
            'Rio',
            'Sedona',
            'Seltos',
            'Sephia',
            'Shuma',
            'Sorento',
            'Soul',
            'Sportage',
            'Stinger',
            'Stonic',
            'Tasman',
            'Telluride',
            'Venga',
            'XCeed',
        ],
        'JEEP': [
            'Avenger',
            'Cherokee',
            'Commander',
            'Compass',
            'Gladiator',
            'Grand Wagoneer',
            'Grand Cherokee',
            'Patriot',
            'Renegade',
            'Wrangler',
        ],
        'SUBARU': [
            'Ascent',
            'B10 Tribeca',
            'B9 Tribeca',
            'BRZ',
            'Baja',
            'Crosstrek',
            'E12',
            'Forester',
            'G3x Justy',
            'Impreza',
            'Justy',
            'Legacy',
            'Levorg',
            'Outback',
            'Solterra',
            'Svx',
            'Trezia',
            'Vivo',
            'WRX',
            'XV',
        ],
        'SEAT': [
            'Alhambra',
            'Altea',
            'Arona',
            'Arosa',
            'Ateca',
            'Cordoba',
            'Cupra',
            'Exeo',
            'Ibiza',
            'Inka',
            'Leon',
            'Marbella',
            'Mii',
            'Terraco',
            'Toledo',
            'Vario',
        ],
        'SUZUKI': [
            'Across',
            'Alto',
            'Baleno',
            'Celerio',
            'Grand Vitara',
            'Ignis',
            'Jimmy',
            'Kizashi',
            'Liana',
            'SX4',
            'SX4 S-Cross',
            'Samurai',
            'Santana',
            'SJ',
            'Splash',
            'Swace',
            'Swift',
            'Vitara',
            'Wagon R',
            'X-90',
            'XL-7',
        ],
        'ALFA ROMEO': [
            '145',
            '146',
            '147',
            '155',
            '156',
            '156 sportwagon',
            '159',
            '159 sportwagon',
            '164',
            '166',
            '33',
            '4C',
            '8C',
            'Brera',
            'Crosswagon q4',
            'Giulia',
            'Giulietta',
            'Gt',
            'Gtv',
            'Junior',
            'Mito',
            'Spider',
            'Stelvio',
            'Tonale',
        ],
        'CHEVROLET': [
            'Z06',
        ],
        'LAND ROVER': [
            'Defender',
            'Discovery',
            'Discovery Sport',
            'Evoque',
            'Freelander',
            'Range Rover Evoque',
            'Range Rover Sport',
            'Range Rover Velar',
            'Range Rover',
        ],
        'MINI': [
            'Aceman',
            'Clubman',
            'Cooper',
            'Cooper cabrio',
            'Cooper s',
            'Cooper s cabrio',
            'Countryman',
            'Coupe',
            'D one',
            'John Cooper Works',
            'One',
            'One cabrio',
            'Paceman',
        ],
        'PORSCHE': [
            '911',
            '924',
            '928',
            '944',
            '991',
            '993',
            'Boxter',
            'Carrera',
            'Cayenne',
            'Cayman',
            'Macan',
            'Panamera',
            'Tycon',
        ],
        'LEXUS': [
            'CT200h',
            'ES300',
            'ES350',
            'GS300',
            'GS350',
            'GS430',
            'GS450h',
            'GX460',
            'GX470',
            'GX550',
            'IS200',
            'IS220d',
            'IS250',
            'IS300',
            'IS350',
            'ISF',
            'LC500',
            'LC500h',
            'LM',
            'LS400',
            'LS430',
            'LS460',
            'LS500',
            'LS500',
            'LS600',
            'LX450d',
            'LX470',
            'LX570',
            'LX600',
            'LX600',
            'LX700h',
            'NX200t',
            'NX300',
            'NX300h',
            'NX350h',
            'NX450',
            'RC300h',
            'RC350',
            'Rx200t',
            'RX300',
            'RX350',
            'RX400',
            'RX450h',
            'RX450h plus',
            'RX500',
            'RX500h',
            'RZ',
            'SC430',
            'TX350',
            'UX200',
            'UX250h',
            'UX300e',
            'UX300h',
        ],
        'CHRYSLER': [
            '200',
            '300c',
            '300m',
            'Crossfire',
            'Gr.voyager',
            'Lebaron',
            'Neon',
            'New yorker',
            'Pacifica',
            'Pt cruiser',
            'Saratoga',
            'Sebring',
            'Stratus',
            'Town And Country',
            'Vison',
            'Voyager',
        ],
        'IVECO': [
            'Massive',
        ],
        'JAGUAR': [
            'Daimler',
            'Daimler six',
            'E-pace',
            'F-pace',
            'F-type',
            'I-pace',
            'S-type',
            'X-type',
            'XE',
            'XF',
            'XJ',
            'XJR',
            'XJS',
            'XK8',
            'XKR',
        ],
        'SAAB': [
            '9-3',
            '9-5',
            '9-7x',
            '900',
            '9000',
        ],
        'GREAT WALL': [
            'Haval H2',
            'Haval H6',
            'Hover Cuv',
            'Hover H5',
            'Hover H6',
            'ORA 03',
            'Poer',
            'Safe',
            'Steed 3',
            'Steed 5',
            'Steed 6',
            'Voleex C10',
            'Voleex C20',
            'Volex C30',
        ],
        'DAIHATSU': [
            'Applause',
            'Coure',
            'Feroza',
            'Gran Move',
            'Materia',
            'Move',
            'Rocky',
            'Siron',
            'Terios',
            'Trevis',
            'Yrv',
        ],
        'INFINITI': [
            'Ex30',
            'Ex35',
            'Ex37',
            'Fx30',
            'Fx35',
            'Fx45',
            'Fx50',
            'G',
            'G Coupe',
            'G Sedan',
            'G37',
            'J',
            'M',
            'Q',
            'Q30',
            'Q50',
            'Q70',
            'QX30',
            'QX50',
            'QX56',
            'QX60',
            'QX70',
            'QX80',
        ],
        'LADA': [
            '1200',
            '1300',
            '1500',
            '1600',
            '2101',
            '21011',
            '21012',
            '21013',
            '2102',
            '2103',
            '2104',
            '2105',
            '21053',
            '2106',
            '2106',
            '21061',
            '2107',
            '2109',
            '21099',
            '2110',
            'Granta',
            'Kalina',
            'Niva',
            'Priora',
            'Samara',
            'Vesta',
            'Xray',
        ],
        'DODGE': [
            'Avenger',
            'Calibra',
            'Caravan',
            'Challenger',
            'Charger',
            'Dakota',
            'Dart',
            'Durango',
            'Interpid',
            'Journey',
            'Magnum',
            'Nitro',
            'RAM 1500',
            'RAM 2500',
            'RAM 3500',
            'RAM',
            'Stealth',
        ],
        'LANCIA': [
            'Aurelia',
            'Beta',
            'Debra',
            'Delta',
            'Flaminia',
            'Flavia',
            'Kappa',
            'Lybra',
            'Musa',
            'Phedra',
            'Thema',
            'Thesis',
            'Voyager',
            'Y',
            'Ypsilon',
            'Zeta',
        ],
        'SSANGYONG': [
            'Actyon',
            'Actyon Sports',
            'Korando',
            'Korando Sports',
            'Kyron',
            'Musso',
            'Rexton',
            'Roius',
            'Tivoli',
            'Torres',
        ],
        'TESLA': [
            'Cybertruck',
            'Model 3',
            'Model S',
            'Model X',
            'Model Y',
            'Y Juniper',
        ],
        'DAEWOO': [
            'Espero',
            'Evanda',
            'Kalos',
            'Korando',
            'Lacetti',
            'Lanos',
            'Leganza',
            'Matiz',
            'Musso',
            'Nexia',
            'Nubira',
            'Rezzo',
            'Tacuma',
            'Tico'
        ],
        'SMART': [
            '1',
            '3',
            'Forfour',
            'Fortwo',
            'MC',
            'Roadster',
            'Smart 1',
            'Smart 3',
        ],
        'DR': [
            '1',
            '3',
            '4',
            '5',
            'DR4',
        ],
        'ROVER': [
            '200',
            '214',
            '216',
            '220',
            '25',
            '400',
            '420',
            '45',
            '600',
            '620',
            '75',
            'Maestro',
            'Streetwise',
        ],
        'ISUZU': [
            'D-Max',
            'Pickup',
            'Rodeo',
            'Trooper',
            'Vehi Cross',
        ],
        'CADILLAC': [
            'ATS',
            'BLS',
            'Brougham',
            'CT6',
            'CTS',
            'DTS',
            'Deville',
            'Eldorado',
            'Escalade',
            'Fleetwood',
            'STS',
            'Seville',
            'Srx',
            'XT4',
            'XT5',
            'XT6',
            'XTS',
            'XLR',
        ]
    }
};